# Generated by Django 2.2.6 on 2019-10-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, max_length=200, null=True)),
                ('views', models.IntegerField()),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
