# Generated by Django 2.2.6 on 2019-10-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='url',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='views',
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='geeks_field',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
