# Generated by Django 2.2.6 on 2020-01-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='img',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='last_modified',
        ),
    ]
