# Generated by Django 2.2.6 on 2019-10-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0002_auto_20191030_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='geeks_field',
            field=models.CharField(db_column='GFG', default='asd', max_length=200),
            preserve_default=False,
        ),
    ]
