# Generated by Django 2.2.6 on 2019-10-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0003_auto_20191030_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='geeks_field',
            field=models.CharField(default='GFG is Best', editable=False, max_length=200),
        ),
    ]
