# Generated by Django 2.2.6 on 2019-10-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0006_auto_20191031_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='geeks_field',
            field=models.CharField(error_messages={'unique': 'The Field you enetered is null.'}, max_length=200, unique=True),
        ),
    ]
