# Generated by Django 2.2.6 on 2019-10-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0007_auto_20191031_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='geeks_field',
            field=models.CharField(error_messages={'blank': 'The Field you enetered is null.'}, max_length=200),
        ),
    ]
