# Generated by Django 2.2.6 on 2019-10-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0009_auto_20191031_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='geeks_field',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
