# Generated by Django 2.2.6 on 2019-11-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0010_auto_20191031_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='geeks_field',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
