# Generated by Django 2.2.6 on 2019-11-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0011_auto_20191101_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='geeks_field',
            field=models.CharField(max_length=200),
        ),
    ]
